server:
  port: 8081

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://114.215.97.217:3306/imetting?characterEncoding\=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true